### ISSUE TITLE
License and contributors

### ISSUE THREAD

**Issue by michael-k** [momorientes/metaEFA#3]
@momorientes @asmaps @c1ko @dansch94: [License](https://github.com/momorientes/metaEFA/blob/11d1a1245795b0b303945168adf7b260952102d9/LICENSE.txt) and [contributors](https://github.com/momorientes/metaEFA/blob/11d1a1245795b0b303945168adf7b260952102d9/CONTRIBUTORS.txt) are still filled with the django boilerplate content.  I'd vote in favor of deleting `CONTRIBUTORS.txt`, but what about the license?  Should we stay with the MIT license (the copyright notice needs an update) or switch to another one?

**Comment by asmaps** [comment]
I'm ok with MIT, but also BSD if you want. Best would be to put this link in contributors: https://github.com/momorientes/metaEFA/graphs/contributors

**Comment by michael-k** [comment]
BSD 2-clause, BSD 3-clause or ISC? http://choosealicense.com/licenses/
I think MIT has the advantage over “BSD” that it's clear which license is meant.

https://github.com/momorientes/metaEFA/graphs/contributors doesn't list @momorientes (author email not added to github account?) and @dansch94 (wiki only).

**Comment by asmaps** [comment]
yes, @momorientes didn't add the used mail to his account => no contribution ("I don't care")

I still think the github contributors page is the best place to link to, because it fills/updates automatically. We can add a "doc contributors" list in the readme or so, to give credit to people that didn't contribute code.

Regarding LICENSE: I don't really care. I don't see the need for GPL or so and BSD, MIT, ISC, etc are very close to each other.
